In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [5]:
if torch.cuda.is_available():
  print("GPU is available!!")
  print(f"Using GPU: {torch.cuda.get_device_name()}")
else:
  print("GPU not available. Using CPU")

  #can select GPU, CPU by going into change runtime option in runtime tab

GPU is available!!
Using GPU: Tesla T4


# **Creating a Tensor**

In [8]:
# using empty
a = torch.empty(2,3)       #values are whatever already exists in the allocated memory at that moment
a

tensor([[7.9874e+17, 2.6186e+20, 6.6564e-33],
        [1.3563e-19, 6.2018e+22, 1.5793e-19]])

In [10]:
# check type
type(a)

torch.Tensor

In [11]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# using rand
torch.rand(2,3)

tensor([[0.4749, 0.1774, 0.7940],
        [0.4412, 0.2128, 0.5109]])

In [21]:
# manual seed
torch.manual_seed(10)            # manual seed gives the same random values every time; without it, random values change on each run
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [22]:
# using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
# using arange
print("Using arange -> ", torch.arange(0,10,2))

# using linspace
print("Using linspace -> ", torch.linspace(0,10,10))

# using eye
print("Using eye -> ", torch.eye(4), sep = '\n')

# using full
print("Using full -> ", torch.full((3,3),2), sep = '\n')

Using arange ->  tensor([0, 2, 4, 6, 8])
Using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> 
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Using full -> 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])


# **Tensor Shapes**

In [35]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
x.shape

torch.Size([3, 3])

In [37]:
# using empty_like
torch.empty_like(x)

tensor([[          864946847, 4612186418624593920, 4614688418536882176],
        [4616690018251964416, 4617941017671237632, 4619192017627381760],
        [4620443017583525888, 4621193617879334912, 4621819117588971520]])

In [38]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [40]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

rand_like function will give error as rand function always assign float values between 0, 1 and here in x we have integer values which are greater than 1

# **Data Types**

In [41]:
# find data type
x.dtype

torch.int64

In [42]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [45]:
torch.tensor([[1,2,3], [9,8,7]], dtype = torch.float64)

tensor([[1., 2., 3.],
        [9., 8., 7.]], dtype=torch.float64)

In [47]:
# using to
x.to(torch.float32)         # changing datatype of existing tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

**Solution to above error problem**

In [49]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440],
        [0.7041, 0.5573, 0.6959]])

# **Mathematical Operations**

# 1) Scalar Operation

In [56]:
# addition
x + 2

tensor([[-1,  0,  1],
        [ 2,  3,  4],
        [ 5,  6,  7]])

In [53]:
# multiplication
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [58]:
# division
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]])

In [60]:
# integer division
x//3

tensor([[0, 0, 1],
        [1, 1, 2],
        [2, 2, 3]])

# 2) Element wise operation

In [62]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.0490, 0.0310, 0.7192],
        [0.8067, 0.8379, 0.7694]])
tensor([[0.6694, 0.7203, 0.2235],
        [0.9502, 0.4655, 0.9314]])


In [67]:
#addition
a+b

tensor([[0.7185, 0.7512, 0.9427],
        [1.7569, 1.3034, 1.7008]])

In [68]:
# multiplication
a*b

tensor([[0.0328, 0.0223, 0.1607],
        [0.7665, 0.3900, 0.7166]])

In [71]:
# division
a/b

tensor([[0.0732, 0.0430, 3.2180],
        [0.8490, 1.7998, 0.8260]])

In [70]:
# int division
a//b

tensor([[0., 0., 3.],
        [0., 1., 0.]])

In [72]:
c = torch.tensor([1,-9,6,-4,0])
c

tensor([ 1, -9,  6, -4,  0])

In [73]:
# abs
torch.abs(c)

tensor([1, 9, 6, 4, 0])

In [74]:
# negative
torch.neg(c)

tensor([-1,  9, -6,  4,  0])

In [81]:
d = torch.tensor([1.9975, -7.8645, -2.4323, 8.5674])

In [79]:
# round
torch.round(d)

tensor([ 2., -8., -2.,  9.])

In [82]:
# ceil
torch.ceil(d)

tensor([ 2., -7., -2.,  9.])

In [83]:
# floor
torch.floor(d)

tensor([ 1., -8., -3.,  8.])

In [87]:
# clamp
torch.clamp(c, min= 1, max = 8)

tensor([1, 1, 6, 1, 1])

# 3) Reduction Operation

In [89]:
e = torch.randint(size = (2,3), low = 2, high = 8)
e

tensor([[7, 3, 3],
        [3, 2, 7]])

In [90]:
torch.sum(e)

tensor(25)

In [91]:
# sum along columns
torch.sum(e, axis = 0)

tensor([10,  5, 10])

In [93]:
# sum along rows
torch.sum(e, axis = 1)

tensor([13, 12])

In [100]:
# mean
f = e.to(dtype = torch.float32)
print(f)
print("mean:", torch.mean(f))
print("mean along columns:", torch.mean(f, axis = 0))

tensor([[7., 3., 3.],
        [3., 2., 7.]])
mean: tensor(4.1667)
mean along columns: tensor([5.0000, 2.5000, 5.0000])


In [101]:
torch.prod(f)

tensor(2646.)

In [102]:
# variance
torch.var(f)

tensor(4.9667)

In [104]:
# standard deviation
torch.std(f)

tensor(2.2286)

In [106]:
# argmax

# tells about tha position of max number
torch.argmax(f)

tensor(0)

In [107]:
torch.argmin(f)

tensor(4)

# 4) Matrix Operation

In [108]:
a1 = torch.randint(size = (2,3), low = 1, high = 6)
b1 = torch.randint(size = (3,4), low = 4, high = 9)
print(a1)
print(b1)

tensor([[2, 2, 3],
        [4, 5, 2]])
tensor([[8, 5, 8, 6],
        [5, 6, 8, 6],
        [6, 8, 8, 8]])


In [109]:
# matrix multiplication
torch.matmul(a1, b1)

tensor([[44, 46, 56, 48],
        [69, 66, 88, 70]])

In [111]:
# dot prod
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3,4])
torch.dot(v1, v2)

tensor(11)

In [112]:
# transpose
torch.transpose(a1, 0, 1)

tensor([[2, 4],
        [2, 5],
        [3, 2]])

Similarly, you can calculate determinat, inverse etc.(linear algebra operation)

# 5) Comparison Operation

In [132]:
a2 = torch.randint(size = (2,3), low = 1, high = 6)
b2 = torch.randint(size = (2,3), low = 1, high = 6)
print(a2)
print(b2)

tensor([[2, 5, 5],
        [2, 2, 1]])
tensor([[2, 4, 2],
        [1, 3, 2]])


In [115]:
# greater than
a2 > b2

tensor([[ True,  True,  True],
        [ True, False, False]])

In [116]:
# equal to
a2 == b2

tensor([[False, False, False],
        [False, False, False]])

Similarly, can check less than, not equal to, greater than equal to etc.

# 6) Special Functions

In [117]:
k = torch.randint(size = (3,2), low = 1, high = 6)
k

tensor([[2, 4],
        [5, 3],
        [5, 5]])

In [118]:
# log
torch.log(k)

tensor([[0.6931, 1.3863],
        [1.6094, 1.0986],
        [1.6094, 1.6094]])

In [127]:
#exponential
torch.exp(k)

tensor([[  7.3891,  54.5981],
        [148.4132,  20.0855],
        [148.4132, 148.4132]])

In [128]:
# square root
torch.sqrt(k)

tensor([[1.4142, 2.0000],
        [2.2361, 1.7321],
        [2.2361, 2.2361]])

In [129]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9820],
        [0.9933, 0.9526],
        [0.9933, 0.9933]])

In [130]:
# softmax
k1 = k.to(dtype = torch.float64)
torch.softmax(k1, dim = 1)          # dim tells which values should be compared and normalized together( i.e. rows should sum 1 or columns)

tensor([[0.1192, 0.8808],
        [0.8808, 0.1192],
        [0.5000, 0.5000]], dtype=torch.float64)

In [131]:
#relu
torch.relu(k)

tensor([[2, 4],
        [5, 3],
        [5, 5]])

# 7) Inplace Operation

In [134]:
m = torch.randint(size = (2,3), low = 1, high = 6)
n = torch.randint(size = (2,3), low = 1, high = 6)
print(m)
print(n)

tensor([[4, 3, 3],
        [5, 1, 1]])
tensor([[3, 1, 3],
        [1, 4, 1]])


In [137]:
# storing in original one rather than creating new tensor
m.add_(n)

tensor([[10,  5,  9],
        [ 7,  9,  3]])

In [139]:
m.relu_()

tensor([[10,  5,  9],
        [ 7,  9,  3]])

# **Copying a tensor**

In [144]:
p = torch.randint(size = (2,3), low = 0, high = 7)
p

tensor([[5, 1, 6],
        [4, 0, 4]])

In [151]:
# Assignment Operation
j = p
print("id of p ->", id(p))
print("id of l ->", id(j))

id of p -> 133140722201408
id of l -> 133140722201408


This can cause issues because any change in p also affects tensor j; to avoid this shared behavior, clone() is used.

In [148]:
l = p.clone()
l

tensor([[5, 1, 6],
        [4, 0, 4]])

In [150]:
print("id of p ->", id(p))
print("id of l ->", id(l))

id of p -> 133140722201408
id of l -> 133140722319296


# **Tensor operation on GPU**

In [152]:
torch.cuda.is_available()

True

In [153]:
device = torch.device('cuda')

In [154]:
# creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.9835, 0.2422, 0.7872],
        [0.0981, 0.6317, 0.2422]], device='cuda:0')

In [155]:
# moving an existing tensor to GPU
p.to(device)

tensor([[5, 1, 6],
        [4, 0, 4]], device='cuda:0')

# **Reshaping Tensors**

In [179]:
h = torch.ones(4,4)
h

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [161]:
# reshape
h.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [180]:
 # flatten
h.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [164]:
# permute

o = torch.rand(2,3,4)
o

tensor([[[0.1699, 0.6641, 0.9510, 0.1006],
         [0.0280, 0.2296, 0.9799, 0.9500],
         [0.0135, 0.6213, 0.5674, 0.9417]],

        [[0.3501, 0.6649, 0.2524, 0.0329],
         [0.5561, 0.2583, 0.4687, 0.3896],
         [0.0956, 0.7927, 0.8453, 0.8823]]])

In [166]:
o.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [168]:
o.permute(1,2,0).shape

torch.Size([3, 4, 2])

In [169]:
# unsqueeze
r = torch.rand(226, 226, 3)       # image size
r.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [170]:
r.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [194]:
# squeeze
d = torch.rand(1, 30)             #squeeze() only removes dimensions of size 1
d.squeeze(0).shape

torch.Size([30])

**squeeze() removes size-1 dimensions**

**unsqueeze() adds a size-1 dimension**

# **Numpy and Pytorch**

Converting numpy array to pytorch and pytorch to numpy array

In [181]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [182]:
b = a.numpy()

In [184]:
type(b)

numpy.ndarray

In [186]:
import numpy as np
c = np.array([1,2,3])

In [189]:
c1 = torch.from_numpy(c)

In [190]:
type(c1)

torch.Tensor