# **Dataset and Dataloader Class**

In PyTorch, **Dataset and DataLoader** are core classes used to efficiently handle and load data during model training.

# Dataset Class

The Dataset class represents the entire dataset. It defines how data samples are stored and accessed. A custom dataset must implement two essential methods ->

*   __len__()

    Returns total number of samples in the dataset.

*   __getitem__(index)

    used to fetch particular row.

The Dataset class is responsible only for data storage and retrieval, not batching or shuffling.

# DataLoader Class

The DataLoader class wraps around a Dataset and controls how data is fed to the model.

It provides the following functionalities ->

*   Divide data into mini-batches
*   Shuffles data
*   supports parallel loadin

During training, the DataLoader returns batches of data instead of individual samples.

In [2]:
import torch
from sklearn.datasets import make_classification

In [3]:
# Step 1: Create a synthetic classification dataset using sklearn
x, y = make_classification(
    n_samples = 10,       # Number of samples
    n_features = 2,       # Number of features
    n_informative = 2,    # Number of informative features
    n_redundant = 0,      # Number of duplicate features
    n_classes = 2,        # Number of classes
    random_state = 42     # For reproducibility
)

In [4]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [8]:
# convert numpy to tensors
x_tensor = torch.from_numpy(x)
y_tensor = torch.from_numpy(y)

In [12]:
x_tensor.shape

torch.Size([10, 2])

In [9]:
x_tensor

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)

In [10]:
y_tensor.dtype

torch.int64

In [11]:
from torch.utils.data import Dataset, DataLoader

In [17]:
class Customdataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [18]:
# creating an object of dataset class

dataset = Customdataset(x_tensor, y_tensor)

In [19]:
len(dataset)

10

In [20]:
dataset[0]

(tensor([ 1.0683, -0.9701], dtype=torch.float64), tensor(1))

In [21]:
# create an object for dataloader class

dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [28]:
# to create batches

for batch_features, batch_label in dataloader:
  print(batch_features)
  print(batch_label)
  print("-"*50)

tensor([[-0.5872, -1.9717],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([1, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
