In [1]:
import torch
import torch.nn as nn

# **Neural Network without hidden layer**

In [4]:
# class should inherit from nn module to use basic offerings of nn

class model(nn.Module):

  def __init__(self, features):     # constructor

    # initializes the parent nn.Module class (without this, PyTorch won’t track parameters)
    super().__init__()

    # input : features, output : of dim 1
    self.linear = nn.Linear(features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [5]:
features = torch.rand(10,5)

In [6]:
features.shape

torch.Size([10, 5])

# Create Model

In [7]:
model = model(features.shape[1])

In [10]:
# model will automatically call forward function
model(features)

tensor([[0.4836],
        [0.4735],
        [0.4220],
        [0.4748],
        [0.4063],
        [0.4743],
        [0.4493],
        [0.4288],
        [0.4734],
        [0.4799]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear.weight

Parameter containing:
tensor([[-0.1833,  0.2381, -0.0467, -0.1412, -0.0129]], requires_grad=True)

In [14]:
model.linear.bias

Parameter containing:
tensor([-0.0918], requires_grad=True)

In [15]:
pip install torchinfo

In [16]:
from torchinfo import summary

In [18]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Neural Network with hidden layer**

In [29]:
class model1(nn.Module):

  def __init__(self, features):     # constructor

    # initializes the parent nn.Module class (without this, PyTorch won’t track parameters)
    super().__init__()

    # input : features, output : of dim 1
    self.linear1 = nn.Linear(features, 3)    # input layer
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)      # hidden layer
    self.Sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.Sigmoid(out)

    return out

In [30]:
features1 = torch.rand(10,5)

In [31]:
model1 = model1(features1.shape[1])

In [26]:
model1(features)

tensor([[0.4138],
        [0.4316],
        [0.3883],
        [0.4138],
        [0.3992],
        [0.3906],
        [0.4017],
        [0.4273],
        [0.4317],
        [0.4261]], grad_fn=<SigmoidBackward0>)

In [33]:
model1.linear1.weight

Parameter containing:
tensor([[-0.2091,  0.0653, -0.2087, -0.1214,  0.3867],
        [-0.3037,  0.0890,  0.1203, -0.1881,  0.2751],
        [ 0.2222,  0.1986, -0.2940,  0.1393, -0.3580]], requires_grad=True)

In [34]:
model1.linear2.weight

Parameter containing:
tensor([[-0.3490, -0.4717,  0.3387]], requires_grad=True)

In [36]:
summary(model1, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Writing each layer separately and defining the forward pass every time can become repetitive and tedious. To simplify this, PyTorch provides the ***nn.Sequential*** container, which allows us to stack layers in sequence. The input is automatically passed through each layer in the order they are defined

In [38]:
class model2(nn.Module):

  def __init__(self, features):     # constructor

    # initializes the parent nn.Module class (without this, PyTorch won’t track parameters)
    super().__init__()

    # input : features, output : of dim 1
    self.network = nn.Sequential(
        nn.Linear(features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid(),
        )

  def forward(self, features):

    out = self.network(features)

    return out

In [39]:
features2 = torch.rand(10,5)

In [40]:
model2 = model2(features2.shape[1])

In [42]:
model2(features)

tensor([[0.4159],
        [0.4236],
        [0.4027],
        [0.4167],
        [0.4106],
        [0.4099],
        [0.4111],
        [0.4104],
        [0.4248],
        [0.4058]], grad_fn=<SigmoidBackward0>)

In [45]:
summary(model2, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model2                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00